//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f3)
//
// On Sun Sep  6 10:44:25 KST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1 const
// get                            O     8 reg
// RDY_get                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_value                      I     8
// EN_put                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkConnected(CLK,
		   RST_N,

		   put_value,
		   EN_put,
		   RDY_put,

		   get,
		   RDY_get);
  input  CLK;
  input  RST_N;

  // action method put
  input  [7 : 0] put_value;
  input  EN_put;
  output RDY_put;

  // value method get
  output [7 : 0] get;
  output RDY_get;

  // signals for module outputs
  wire [7 : 0] get;
  wire RDY_get, RDY_put;

  // ports of submodule left
  wire [7 : 0] left$get, left$put_value;
  wire left$EN_put;

  // ports of submodule right
  wire [7 : 0] right$get, right$put_value;
  wire right$EN_put;

  // action method put
  assign RDY_put = 1'd1 ;

  // value method get
  assign get = right$get ;
  assign RDY_get = 1'd1 ;

  // submodule left
  mkStage left(.CLK(CLK),
	       .RST_N(RST_N),
	       .put_value(left$put_value),
	       .EN_put(left$EN_put),
	       .RDY_put(),
	       .get(left$get),
	       .RDY_get());

  // submodule right
  mkStage right(.CLK(CLK),
		.RST_N(RST_N),
		.put_value(right$put_value),
		.EN_put(right$EN_put),
		.RDY_put(),
		.get(right$get),
		.RDY_get());

  // submodule left
  assign left$put_value = put_value ;
  assign left$EN_put = EN_put ;

  // submodule right
  assign right$put_value = left$get + put_value ;
  assign right$EN_put = EN_put ;
endmodule  // mkConnected

