//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f3)
//
// On Sun Sep  6 10:44:25 KST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1 const
// get                            O     8 reg
// RDY_get                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_value                      I     8
// EN_put                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkStage(CLK,
	       RST_N,

	       put_value,
	       EN_put,
	       RDY_put,

	       get,
	       RDY_get);
  input  CLK;
  input  RST_N;

  // action method put
  input  [7 : 0] put_value;
  input  EN_put;
  output RDY_put;

  // value method get
  output [7 : 0] get;
  output RDY_get;

  // signals for module outputs
  wire [7 : 0] get;
  wire RDY_get, RDY_put;

  // register state
  reg [7 : 0] state;
  wire [7 : 0] state$D_IN;
  wire state$EN;

  // action method put
  assign RDY_put = 1'd1 ;

  // value method get
  assign get = state ;
  assign RDY_get = 1'd1 ;

  // register state
  assign state$D_IN = put_value + 8'd1 ;
  assign state$EN = EN_put ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        state <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    state = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkStage

