//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f3)
//
// On Sun Sep  6 10:44:27 KST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1 const
// get                            O    12 reg
// RDY_get                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_value                      I    12
// EN_put                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkWide(CLK,
	      RST_N,

	      put_value,
	      EN_put,
	      RDY_put,

	      get,
	      RDY_get);
  input  CLK;
  input  RST_N;

  // action method put
  input  [11 : 0] put_value;
  input  EN_put;
  output RDY_put;

  // value method get
  output [11 : 0] get;
  output RDY_get;

  // signals for module outputs
  wire [11 : 0] get;
  wire RDY_get, RDY_put;

  // register implementation_state
  reg [11 : 0] implementation_state;
  wire [11 : 0] implementation_state$D_IN;
  wire implementation_state$EN;

  // action method put
  assign RDY_put = 1'd1 ;

  // value method get
  assign get = implementation_state ;
  assign RDY_get = 1'd1 ;

  // register implementation_state
  assign implementation_state$D_IN = put_value + 12'd1 ;
  assign implementation_state$EN = EN_put ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        implementation_state <= `BSV_ASSIGNMENT_DELAY 12'd0;
      end
    else
      begin
        if (implementation_state$EN)
	  implementation_state <= `BSV_ASSIGNMENT_DELAY
	      implementation_state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    implementation_state = 12'hAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkWide

