'use strict';

(function expose(root) {
    const ko = {
        'Hardware · Experimental': '하드웨어 · 실험 기능',
        'Design': '설계', 'Registered hardware root': '현재 하드웨어 설계',
        'Settings': '설정', 'Advanced inputs and diagnostics': '고급 입력 및 진단',
        'Choose BSV source': '추가 BSV 소스 선택', 'Connect RTL result': 'RTL 결과 연결',
        'Workspace source settings': '작업 영역 소스 설정', 'Details': '정보', 'Details for {name}': '{name} 정보',
        'Connect an RTL result': 'RTL 결과 연결',
        'Choose one result explicitly. Source correspondence is not inferred.': '연결할 결과를 직접 선택하세요. 소스 대응은 추정하지 않습니다.',
        'Choose a different artifact file…': '다른 RTL 결과 파일 선택…',
        'Source correspondence is not established.': '소스 대응이 확인되지 않았습니다.',
        'The artifact changed. This is the previously captured implementation.': 'RTL 결과가 변경되었습니다. 현재 화면은 이전에 읽은 구현입니다.',
        'Source changed. This is the captured previous structure; refresh to analyse saved changes.': '소스가 변경되었습니다. 현재 화면은 이전에 읽은 구조입니다. 저장된 변경 내용을 분석하려면 새로 고침하세요.',
        'Register artifact': 'RTL 결과 연결', 'Register bundle': '대응 자료 연결',
        'Register origin capture': '원인 추적 자료 연결', 'Refresh registered input': '입력 새로 고침',
        'Theme': '테마', 'Color theme': '색 테마', 'Dark': '어둡게', 'Light': '밝게', 'High contrast': '고대비',
        'Implementation': 'RTL 구현', 'Implementation provider': 'RTL 분석 자료',
        'Instrumented capture': '계측 자료', 'Stock metadata': '컴파일러 메타데이터', 'Export SVG': 'SVG 내보내기',
        'Checking installed build...': '설치된 빌드 확인 중…',
        'Finding BSV sources in this workspace...': '현재 작업 영역에서 BSV 소스 찾는 중…',
        'Hardware navigation': '하드웨어 탐색', 'Back': '뒤로', 'Forward': '앞으로', 'Up': '상위',
        'Previous analysis visit (Alt+Left)': '이전 분석 상태 (Alt+Left)',
        'Next analysis visit (Alt+Right)': '다음 분석 상태 (Alt+Right)',
        'Actual hierarchy parent': '실제 상위 모듈', 'Return BSV': 'BSV로 돌아가기',
        'BSV occurrence path': 'BSV 인스턴스 경로', 'Actual RTL occurrence path': '실제 RTL 인스턴스 경로',
        'View RTL Implementation': 'RTL 구현 보기', 'RTL result not connected': 'RTL 결과 미연결',
        'Fit structure': '전체 구조 맞춤', 'Fit selection': '선택 대상 맞춤',
        'Show the complete current topology; fold supplementary labels': '현재 표시 범위의 전체 구조를 맞춥니다. 부가 상세는 접힙니다.',
        'Read the selected object and local relationships; other structure may remain outside the viewport': '선택 대상과 관련 범위를 맞춥니다. 나머지 구조는 화면 밖에 있을 수 있습니다.',
        'Hide Inspector': '상세 닫기', 'Show Inspector': '상세 열기',
        'Current hardware scene': '현재 하드웨어 화면', 'BSV Architecture': 'BSV 구조도', 'RTL Implementation': 'RTL 구현',
        'Hardware schematic': '하드웨어 구조도', 'Hardware details': '선택 상세',
        'Clear': '선택 해제', 'Clear selection': '선택 해제', 'Clear selection (Escape)': '선택 해제 (Escape)',
        'Providers and capabilities': '분석 자료와 지원 범위', 'Choose hardware input': '하드웨어 입력 상태',
        'Open your BSV design': 'BSV 설계 열기',
        'Workspace sources are discovered automatically. Select a design when several roots are found.': '작업 영역 소스를 자동으로 찾습니다. 설계가 여러 개면 열 대상을 선택하세요.',
        'Source analysis works without a compiler or RTL result. Additional inputs are available in Settings.': '컴파일러나 RTL 결과 없이 소스 구조를 볼 수 있습니다. 추가 입력은 설정에서 연결하세요.',
        'Click a block to see inside.': '블록을 클릭하면 내부로 들어갑니다.',
        'Select a port or connection to inspect related code.': '포트나 연결을 선택하면 관련 코드를 확인할 수 있습니다.',
        'Overview · Select an interface for its details.': '개요 보기 · 인터페이스 상세는 선택하면 표시됩니다.',
        'BSV source analysis': 'BSV 소스 분석',
        'Analyzing BSV source only. Connect a compiler result to inspect RTL.': '현재 BSV 소스만 분석 중입니다. RTL 구현을 보려면 컴파일 결과를 연결하세요.',
        'BSV relation': 'BSV 관계', 'RTL net': 'RTL 배선', 'Partial origin': '부분 원인 대응',
        'Connection legend': '연결 범례', 'Dot = junction; crossing without dot = separate': '점은 접합입니다. 점 없는 교차는 별개 연결입니다.',
        'Select a design': '설계 선택', 'Opening {name}...': '{name} 여는 중…',
        'Could not open {name}. Still showing {current}.': '{name}을 열지 못했습니다. 현재 {current} 화면을 유지하고 있습니다.',
        'Some connections could not be placed. Module structure and source analysis remain available.': '일부 연결의 배치가 완료되지 않았습니다. 모듈 구조와 원문 분석은 사용할 수 있습니다.',
        'Retry': '다시 시도', 'Show connections': '연결 목록 보기', 'Copy diagnostics': '진단 복사', 'Problem details': '문제 상세',
        'Current module: {name}': '현재 모듈: {name}', 'Selected: {name}': '선택: {name}',
        'Structure overview': '전체 구조 개요', 'Selection detail': '선택 대상 상세', 'Manual viewport': '수동 확대 / 이동',
        'State connections appear when you select storage or behavior.': '저장소나 동작을 선택하면 관련 상태 연결이 표시됩니다.',
        'Outside: {blocks} blocks, {routes} route continuations': '현재 화면 밖: 블록 {blocks}개, 이어지는 연결 {routes}개',
        'All displayed structure in view': '현재 표시 범위의 전체 구조',
        'BSV files analyzed: {count} · Source-based': 'BSV 파일 {count}개 분석 · 소스 기반',
        'No BSV files found': 'BSV 파일을 찾지 못했습니다',
        'BSV files were found, but no hardware module roots are available.': 'BSV 파일은 발견했지만 하드웨어 모듈 root가 없습니다.',
        'Sources changed. Preparing the saved revision...': '소스 변경을 감지했습니다. 저장된 버전 준비 중…',
        'Choose a source design': '열 소스 설계 선택',
        'Each design is analysed independently; no compiler is run.': '각 설계는 독립적으로 분석합니다. 컴파일러는 실행하지 않습니다.',
        'Finding BSV sources in the current workspace…': '현재 작업 영역에서 BSV 소스 찾는 중…',
        'Updated sources are ready. Opening the current module…': '변경된 소스가 준비되었습니다. 현재 모듈 여는 중…',
        'Unsaved edits are present. The structure uses saved source; old ranges are not applied to changed text.': '미저장 변경이 있습니다. 구조는 저장된 소스 기준입니다. 변경된 텍스트에 과거 원문 범위를 적용하지 않습니다.',
        'The selected workspace folder is no longer open': '선택한 작업 영역 폴더가 더 이상 열려 있지 않습니다',
        'Automatic source discovery is not enabled for this workspace': '이 작업 영역의 자동 소스 탐색이 꺼져 있습니다',
        'Sources changed. Refresh to analyze the saved revision.': '소스가 변경되었습니다. 저장된 버전을 분석하려면 새로 고침하세요.',
        'Source inventory and exclusions': '발견한 소스와 제외 이유',
        'Connections and code ({count})': '연결과 코드 ({count}개)',
        'Original relations ({count})': '원본 관계 ({count}개)', 'Original relations: {count}': '원본 관계: {count}개',
        'Relation family': '관계 종류', 'Endpoint A': '첫 번째 접점', 'Endpoint B': '두 번째 접점',
        'Binding or alias; no data-flow direction is asserted.': '바인딩 또는 별칭 관계입니다. 데이터 흐름 방향을 뜻하지 않습니다.',
        'Source relation; this is not an RTL net.': '소스에서 확인된 관계입니다. RTL 배선과 구분됩니다.',
        'The previous source revision remains displayed.': '이전 소스 버전의 화면을 유지하고 있습니다.',
        'Diagnostics copied': '진단을 복사했습니다', 'Could not open {name}.': '{name}을 열지 못했습니다.',
        'Details remain available in the Inspector.': '상세 창에서 계속 확인할 수 있습니다.',
        '{count} connections await placement': '연결 {count}개의 배치가 보류되었습니다',
        'Instance context': '인스턴스 정보', 'Definition': '정의', 'Selected path': '선택 경로',
        'Child instances': '하위 모듈', 'Storage': '저장소', 'Typed methods': '메서드', 'BSV owner': 'BSV 소속',
        'Direct children': '직접 하위 모듈', 'Interfaces': '인터페이스', 'No direct children': '직접 하위 모듈 없음',
        'Open {name}': '{name} 내부 보기', 'Click to see inside {name}': '클릭하여 {name} 내부 보기',
        'Source': '원문', 'Open source': '원문 열기', 'Source: {path}': '원문: {path}',
        'Source and implementation details': '원문 및 구현 근거',
        'Hardware analysis': '연결과 코드', 'Readers / writers': '읽기 / 쓰기 동작', 'Method code': '메서드 코드',
        'Source mode': '원문 버전', 'Captured build source': '분석 시점 소스', 'Current source (freshness checked)': '현재 소스 (변경 확인)',
        'Source options': '원문 버전 설정', 'Behavior code': '동작 코드', 'Call context': '호출 관계',
        'Evidence details': '분석 근거 상세',
        'Behavior code: {name}': '동작 코드: {name}', 'Update code: {name}': '갱신 코드: {name}',
        'Call / argument context: {name}': '호출 / 인자 관계: {name}', 'Open source owner: {name}': '소속 모듈에서 보기: {name}',
        'Current source': '현재 소스',
        'Partial source inventory. Review source settings.': '일부 소스만 확인했습니다. 소스 설정에서 제한을 확인하세요.',
        'Only {count} of {total} source designs are listed.': '설계 {total}개 중 {count}개만 목록에 표시됩니다.',
        'No parent instance found in the analyzed sources.': '분석한 소스에서 상위 인스턴스를 찾지 못한 설계입니다.',
        'Source design candidate; hierarchy contains a cycle.': '계층에 순환 참조가 있는 설계 후보입니다.',
        'Used inside another source module.': '다른 모듈 내부에서 사용하는 설계입니다.',
        'Choose a design': '설계 선택',
        'Found {count} BSV files. Choose a design to open.': 'BSV 파일 {count}개를 찾았습니다. 열 설계를 선택하세요.',
        'Design selection closed. The current design is unchanged.': '설계 선택을 닫았습니다. 현재 설계는 그대로 유지합니다.',
        'This design exceeds the supported analysis size. Choose a smaller module.': '이 설계는 지원하는 분석 크기를 초과합니다. 더 작은 모듈을 선택하세요.',
        'This design history is full. Start a new history to open another design.': '설계 탐색 기록이 가득 찼습니다. 다른 설계를 열려면 새 탐색 기록을 시작하세요.',
        'Open {name} in a new history': '{name}을 새 탐색 기록으로 열기',
        'A new history replaces previous Back and Forward entries only after the design opens.': '설계가 열린 뒤에만 기존 뒤로·앞으로 탐색 기록을 새 기록으로 바꿉니다.',
        'Finishing the new design history...': '새 설계 탐색 기록을 확정하는 중…',
        'The design is open, but its state could not be saved for restart.': '설계는 열렸지만 다음 실행을 위한 상태를 저장하지 못했습니다.',
        'Still showing {name}.': '현재 {name} 화면을 유지하고 있습니다.',
        'RTL result connected. BSV source correspondence is not attached.': 'RTL 결과가 연결됐습니다. BSV 원문 대응은 연결되지 않았습니다.',
        'BSV sources and RTL result loaded.': 'BSV 소스와 RTL 결과를 불러왔습니다.',
        'Showing {returned} of {total} designs · limit {limit}; narrow the source scope for more.': '설계 {total}개 중 {returned}개 표시 · 제한 {limit}개. 더 확인하려면 소스 범위를 좁히세요.',
        'The selected object is no longer available in this revision. The current module is preserved.': '새 소스에서 선택한 객체를 찾을 수 없습니다. 현재 모듈은 유지합니다.',
        'The previous module is no longer available in this revision. Showing the selected design overview.': '새 소스에서 이전 모듈을 찾을 수 없습니다. 선택한 설계의 개요를 표시합니다.',
        'The workspace source revision changed. Showing its source-based design overview.': '작업 영역 소스가 변경되어 소스 기반 설계 개요를 표시합니다.',
        'No BSV files were found inside this workspace. Check source settings or choose source inputs in Settings.': '작업 영역에서 BSV 파일을 찾지 못했습니다. 소스 설정을 확인하거나 설정에서 소스를 직접 선택하세요.',
        'Declared storage': '선언된 저장소', 'Constructor': '생성자', 'Initial expression': '초기값', 'Written by': '쓰기 동작', 'Read by': '읽기 동작',
        'Source interface group': '인터페이스', 'Meaning': '의미', 'Members': '포함 메서드', 'Member methods': '포함 메서드',
        'Interface grouping, not a physical port': '소스 인터페이스 묶음', 'Typed contact': '메서드 접점',
        'Category': '분류', 'Direction': '방향', 'Input': '입력', 'Result': '결과', 'Related behavior': '관련 동작',
        'Connection evidence': '연결 근거', 'Compiler port mappings': '컴파일러 포트 대응',
        'Implementation correspondence': 'RTL 대응 근거', 'Source behavior, not a physical hardware block': '소스에 선언된 동작',
        'Same net': '같은 신호', 'Drivers / loads': '구동 / 부하', 'Input dependencies': '입력 의존 관계', 'Output dependents': '출력 영향 관계',
        'Open approved source slice': '원문 열기', 'Code Drawer / read-only original source': '원문 코드 · 읽기 전용',
        'Readers': '읽기 동작', 'Writers': '쓰기 동작', 'Analyze behavior': '동작 분석', 'Analyze call context': '호출 분석',
        'Input source dependencies': '입력 소스 관계', 'Output source dependents': '출력 소스 관계',
        'Explain implementation mapping': 'RTL 대응 근거 보기',
        'No RTL result is connected. Source navigation is available.': 'RTL 결과가 연결되지 않았습니다. 소스 구조 탐색은 사용할 수 있습니다.'
    };
    function translate(locale, key, values = {}) {
        const template = /^ko(?:-|$)/i.test(locale || '') ? ko[key] || key : key;
        return template.replace(/\{([A-Za-z]+)\}/g, (token, name) => Object.hasOwn(values, name) ? String(values[name]) : token);
    }
    const api = { translate, t: (key, values) => translate(root.document?.documentElement?.lang || 'en', key, values) };
    if (typeof module === 'object' && module.exports) module.exports = api;
    if (root.document) root.BsvHardwareStrings = api;
})(globalThis);
